setwd("C:/Users/Agata_P/Documents/Magisterka/fe-s-o")

plot(1, type="n", xlab="pH", ylab="Eh (V)", ylim=c(-0.8, 0.6), xlim=c(2, 12), xaxs="i",yaxs="i")

options(OutDec= ",") 

linia1 <- read.delim2("linia1.txt",header=FALSE)
linia2a <- read.delim2("linia2a.txt",header=FALSE)
linia2b <- read.delim2("linia2b.txt",header=FALSE)
linia3 <- read.delim2("linia3.txt",header=FALSE)
linia4 <- read.delim2("linia4.txt",header=FALSE)
linia5 <- read.delim2("linia5.txt",header=FALSE)
linia6 <- read.delim2("linia6.txt",header=FALSE)
linia7 <- read.delim2("linia7.txt",header=FALSE)
linie_przeryw_1 <- read.delim2("linie_przeryw_1.txt",header=FALSE)
linie_przeryw_2 <- read.delim2("linie_przeryw_2.txt",header=FALSE)
poly1 <- read.delim2("poly1.txt",header=FALSE)
poly2 <- read.delim2("poly2.txt",header=FALSE)
poly3 <- read.delim2("poly3.txt",header=FALSE)
poly4 <- read.delim2("poly4.txt",header=FALSE)

polygon(poly1$V1,poly1$V2,col="gray90")
polygon(poly2$V1,poly2$V2,col="gray80")
polygon(poly3$V1,poly3$V2,col="gray70")
polygon(poly4$V1,poly4$V2,col="gray60")
polygon(linia1$V1,linia1$V2)
polygon(linia2a$V1,linia2a$V2)
polygon(linia2b$V1,linia2b$V2)
polygon(linia3$V1,linia3$V2)
polygon(linia4$V1,linia4$V2)
polygon(linia5$V1,linia5$V2)
polygon(linia6$V1,linia6$V2)
polygon(linia7$V1,linia7$V2)
polygon(linie_przeryw_1$V1,linie_przeryw_1$V2,lty=2)
polygon(linie_przeryw_2$V1,linie_przeryw_2$V2,lty=2)
